// Generated by https://quicktype.io

import { ConductorEntity } from "./conductor.entity";
import { DetalleActividadEntity } from "./detalleActividad.entity";
import { SolicitudEntity } from "./solicitud.entity";
import { VehiculoEntity } from "./vehiculo.entity";

export interface ActividadEntity {
    idActividad:           number;
    conductor:             ConductorEntity;
    vehiculo:              VehiculoEntity;
    solicitud:             SolicitudEntity;
    descripcion:           string;
    fechaCreada:           string;
    estado:                boolean;
    listaDetalleActividad: DetalleActividadEntity[];
}


