// Generated by https://quicktype.io

import { DetalleCliente } from "./detalleCliente.entity";
import { TipoCliente } from "./tipoCliente.entity";

export interface ClienteEntity {
    idCliente:      number;
    ruc:            string;
    nombres:        string;
    telefono:       string;
    email:          string;
    estado:         boolean;
    tipoCliente:    TipoCliente;
    detalleCliente: DetalleCliente;
}




