// Generated by https://quicktype.io

import { ClienteEntity } from "./cliente.entity";
import { DetalleSolicitudEntity } from "./detalleSolicitud.entity";
import { ServicioEntity } from "./servicios.entity";

export interface SolicitudEntity {
    idSolicitud:           number;
    servicio:              ServicioEntity;
    cliente:               ClienteEntity;
    descripcion:           string;
    fechaSolicitada:       string;
    estado:                boolean;
    listaDetalleSolicitud: DetalleSolicitudEntity[];
}


