// Generated by https://quicktype.io

import { DetalleClienteModel } from "./detalleCliente.model";
import { TipoClienteModel } from "./tipoCliente.model";

export interface ClienteModel {
    idCliente:      number;
    ruc:            string;
    nombres:        string;
    telefono:       string;
    email:          string;
    estado:         boolean;
    tipoCliente:    TipoClienteModel;
    detalleCliente?: DetalleClienteModel;
}




