// Generated by https://quicktype.io

export interface PageSpringBoot<E> {
    content:          E[];
    pageable:         Pageable;
    last:             boolean;
    totalElements:    number;
    totalPages:       number;
    size:             number;
    number:           number;
    sort:             Sort;
    first:            boolean;
    numberOfElements: number;
    empty:            boolean;
}


export interface DetalleCliente {
    idDetalleCliente: number;
    genero:           Genero;
    apellidoPaterno:  string;
    apellidoMaterno:  string;
    dni:              string;
    edad:             string;
    foto:             null;
}

export interface Genero {
    idGenero: number;
    tipo:     string;
}

export interface TipoCliente {
    idTipoCliente: number;
    tipo:          string;
}

export interface Pageable {
    sort:       Sort;
    offset:     number;
    pageNumber: number;
    pageSize:   number;
    unpaged:    boolean;
    paged:      boolean;
}

export interface Sort {
    empty:    boolean;
    sorted:   boolean;
    unsorted: boolean;
}
